[package]
name = "taskwarrior-tui"
version = "0.13.28"
license = "MIT"
description = "A Taskwarrior Terminal User Interface"
repository = "https://github.com/kdheepak/taskwarrior-tui/"
homepage = "https://kdheepak.com/taskwarrior-tui"
readme = "README.md"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
edition = "2018"
keywords = ["taskwarrior", "tui"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["crossterm-backend"]
crossterm-backend = ["tui/crossterm", "crossterm"]

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes", "unstable"] }
better-panic = "0.2.0"
cassowary = "0.3.0"
chrono = "0.4"
clap = "3.0.0-beta.2"
crossterm = { version = "0.17", optional = true, default-features = false, features = ["event-stream"] }
dirs = "2.0.2"
futures = "0.3"
futures-timer = "3.0"
itertools = "0.9"
lazy_static = "1.4.0"
rand = "0.7"
regex = "1"
rustyline = "8"
rustyline-derive = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shellexpand = "2.1"
shlex = "0.1"
task-hookrs = { git = "https://github.com/kdheepak/task-hookrs" }
tui = { version = "0.12", optional = true, default-features = false }
unicode-segmentation = "1.6"
unicode-truncate = "0.2"
unicode-width = "0.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"

[package.metadata.rpm]
package = "taskwarrior-tui"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
taskwarrior-tui = { path = "/usr/bin/taskwarrior-tui" }

[profile.release]
debug = true
