[package]
name = "taskwarrior-tui"
version = "0.1.0"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["termion-backend"]
termion-backend = ["tui/termion", "termion"]
crossterm-backend = ["tui/crossterm", "crossterm"]

[dependencies]
clap = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
task-hookrs = "0.7.0"
rand = "0.7"
shlex = "0.1.1"
chrono = "0.4"
unicode-width = "0.1"
tui = { version = "0.10.0", optional = true, default-features = false }
termion = { version = "1.5", optional = true, default-features = false }
crossterm = { version = "0.17", optional = true, default-features = false }
