[package]
name = "taskwarrior-tui"
version = "0.6.3"
license = "MIT"
description = "A Taskwarrior Terminal User Interface"
repository = "https://github.com/kdheepak/taskwarrior-tui/"
homepage = "https://kdheepak.com/taskwarrior-tui"
readme = "README.md"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
edition = "2018"
keywords = ["taskwarrior", "tui"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["crossterm-backend"]
crossterm-backend = ["tui/crossterm", "crossterm"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = "2.33"
task-hookrs = { git = "https://github.com/matthiasbeyer/task-hookrs" }
rand = "0.7"
shlex = "0.1"
chrono = "0.4"
unicode-width = "0.1"
tui = { version = "0.10", optional = true, default-features = false }
crossterm = { version = "0.17", optional = true, default-features = false }
