[package]
name = "taskwarrior-tui"
version = "0.19.3"
license = "MIT"
description = "A Taskwarrior Terminal User Interface"
repository = "https://github.com/kdheepak/taskwarrior-tui/"
homepage = "https://kdheepak.com/taskwarrior-tui"
readme = "README.md"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
edition = "2018"
keywords = ["taskwarrior", "tui"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["crossterm-backend"]
crossterm-backend = ["tui/crossterm", "crossterm"]

[dependencies]
anyhow = "1.0.52"
async-std = { version = "1.10.0", features = ["attributes", "unstable"] }
better-panic = "0.2.0"
cassowary = "0.3.0"
chrono = "0.4.19"
clap = { version = "3.0.0", features = ["derive"] }
crossterm = { version = "0.22.1", optional = true, default-features = false, features = ["event-stream"] }
dirs = "4.0.0"
futures = "0.3.19"
futures-timer = "3.0.2"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.14"
log4rs = "1.0.0"
path-clean = "0.1.0"
rand = "0.8.4"
regex = "1.5.4"
rustyline = "9.1.2"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
shellexpand = "2.1.0"
shlex = "1.1.0"
task-hookrs = { git = "https://github.com/kdheepak/task-hookrs" }
tui = { version = "0.16.0", optional = true, default-features = false }
unicode-segmentation = "1.8.0"
unicode-truncate = "0.2.0"
unicode-width = "0.1.9"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
versions = "3.0.3"

[package.metadata.rpm]
package = "taskwarrior-tui"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
taskwarrior-tui = { path = "/usr/bin/taskwarrior-tui" }

[profile.release]
debug = 1
incremental = true
lto = "off"

[build-dependencies]
clap = { version = "3.0.0", features = ["derive"] }
clap_complete = "3.0.0"
shlex = "1.1.0"
