[package]
name = "taskwarrior-tui"
version = "0.25.1"
license = "MIT"
description = "A Taskwarrior Terminal User Interface"
repository = "https://github.com/kdheepak/taskwarrior-tui/"
homepage = "https://kdheepak.com/taskwarrior-tui"
readme = "README.md"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
edition = "2018"
keywords = ["taskwarrior", "tui"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["crossterm-backend"]
crossterm-backend = ["tui/crossterm", "crossterm"]

[dependencies]
anyhow = "1.0.72"
better-panic = "0.3.0"
cassowary = "0.3.0"
chrono = "0.4.26"
clap = { version = "4.3.19", features = ["derive"] }
crossterm = { version = "0.26.1", optional = true, default-features = false, features = [
  "event-stream",
] }
dirs = "5.0.1"
futures = "0.3.28"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.19"
log4rs = "1.2.0"
path-clean = "1.0.1"
rand = "0.8.5"
regex = "1.9.1"
rustyline = { version = "12.0.0", features = ["with-file-history", "derive"] }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
shellexpand = "3.1.0"
shlex = "1.1.0"
task-hookrs = "0.9.0"
tokio = { version = "1.29.1", features = ["full"] }
tokio-stream = "0.1.14"
tui = { package = "ratatui", version = "0.22.0" }
unicode-segmentation = "1.10.1"
unicode-truncate = "0.2.0"
unicode-width = "0.1.10"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
versions = "5.0.0"

[package.metadata.rpm]
package = "taskwarrior-tui"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
taskwarrior-tui = { path = "/usr/bin/taskwarrior-tui" }

[profile.release]
debug = 1
incremental = true
lto = "off"

[build-dependencies]
clap = { version = "4.3.19", features = ["derive"] }
clap_complete = "4.3.2"
shlex = "1.1.0"
