name: Docs
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python3 -m pip install mkdocs            # install mkdocs
          python3 -m pip install mkdocs-material   # install material theme
          python3 -m pip install mkdocs-exclude    # install mkdocs exclude
          python3 -m pip install pygments pymdown-extensions mkdocs-material-extensions termcolor mkdocs-material mkdocs-macros-plugin
      - name: Copy README
        run: |
          cp README.md docs/index.md
      - name: Build site
        run: mkdocs build
      - name: Github Pages Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v1.1.13
        with:
          publish-dir: ./site
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5
      - name: Documentation Preview
        uses: ProjectPythia/actions/comment-netlify-preview-in-pr@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-url: ${{ steps.netlify.outputs.deploy-url }}
